### ISSUE TITLE
Trino won't start

### ISSUE THREAD

**Issue by ghpu** [scie-nz/walden#3]
Trying on minikube, both trino-coordinator and trino-worker pods crash at startup, with log error :

cat: etc/node.properties.template: No such file or directory
cat: etc/config.properties.template: No such file or directory
ERROR: JVM config file is missing: /trino-server-360/etc/jvm.config

**Comment by bogdanstate** [comment]
@ghpu, this is likely due to a version mismatch -- the Docker files currently have version 363, whereas the K8s config uses version 360. Should be an easy fix -- just grep for 360 and replace with 363. Will try to get to this myself today.

**Comment by bogdanstate** [comment]
@ghpu, managed to fix this, trino has now been updated to 368 and I have tested the example in the README -- works now!
